export const UiStateStatus = {
  SIGNED_IN: 'SIGNED_IN',
  SIGN_UP: 'SIGN_UP',
  CONFIRM_SIGN_UP: 'CONFIRM_SIGN_UP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUBMIT: 'FORGOT_PASSWORD_SUBMIT',
};
