export const ActionType = {
  /* appReducer */
  SET_UI_STATE: 'SET_UI_STATE',
  CHECK_AUTH_USER: 'CHECK_AUTH_USER',
  CHECK_AUTH_USER_ERROR: 'CHECK_AUTH_USER_ERROR',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  CONFIRM_SIGN_UP_SUCCESS: 'CONFIRM_SIGN_UP_SUCCESS',
  RESET_APP_STATE: 'RESET_APP_STATE',
  AUTH_IS_LOADING: 'AUTH_IS_LOADING',
  AUTH_ERROR: 'AUTH_ERROR',

  /* booksReducer */
  BOOKS_IS_LOADING: 'BOOKS_IS_LOADING',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  SET_ADD_BOOK_SUCCESS: 'SET_ADD_BOOK_SUCCESS',
  SET_EDIT_BOOK_SUCCESS: 'SET_EDIT_BOOK_SUCCESS',
};
