export const ActionType = {
  SET_USER: 'SET_USER',
  SET_UI_STATE: 'SET_UI_STATE',
  SET_IS_LOADING: 'SET_IS_LOADING',
  GET_BOOKS: 'GET_BOOKS',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  SET_UPDATED_BOOK: 'SET_UPDATED_BOOK',
};
