export const ActionType = {
  SET_USER: 'SET_USER',
  SET_UI_STATE: 'SET_UI_STATE',
  SET_IS_LOADING: 'SET_IS_LOADING',
  GET_BOOKS: 'GET_BOOKS',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOK: 'GET_BOOK',
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  SET_ADD_BOOK: 'SET_ADD_BOOK',
  SET_ADD_BOOK_SUCCESS: 'SET_ADD_BOOK_SUCCESS',
  SET_EDIT_BOOK: 'SET_EDIT_BOOK',
  SET_EDIT_BOOK_SUCCESS: 'SET_EDIT_BOOK_SUCCESS',
  SET_UPDATED_BOOK: 'SET_UPDATED_BOOK',
};
